// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"Gf-Vben/app/model/internal"
)

// AppUserRole is the golang structure for table app_user_role.
type AppUserRole internal.AppUserRole

// Fill with you ideas below.
