// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"Gf-Vben/app/model/internal"
)

// AppRole is the golang structure for table app_role.
type AppRole internal.AppRole

// Fill with you ideas below.
