// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"Gf-Vben/app/model/internal"
)

// AppUser is the golang structure for table app_user.
type AppUser internal.AppUser

// Fill with you ideas below.
