// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "Gf-Vben/internal/logic/curd"
	_ "Gf-Vben/internal/logic/example"
	_ "Gf-Vben/internal/logic/router"
	_ "Gf-Vben/internal/logic/user"
)
