// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Permission is the golang structure of table permission for DAO operations like Where/Data.
type Permission struct {
	g.Meta   `orm:"table:permission, do:true"`
	Id       interface{} //
	Parent   interface{} // 父级权限ID 0为权限域
	Value    interface{} //
	Desc     interface{} //
	CreateAt *gtime.Time //
	UpdateAt *gtime.Time //
	DeleteAt *gtime.Time //
	Name     interface{} //
	Type     interface{} // 1 权限域 2 权限组 3 权限
}
