// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// AppUser is the golang structure for table app_user.
type AppUser struct {
	Id       int         `orm:"id,primary"       json:"id"`       // primary id
	Username string      `orm:"username,primary" json:"username"` // username
	Password string      `orm:"password"         json:"password"` // password
	Note     string      `orm:"note"             json:"note"`     //
	NickName string      `orm:"nick_name"        json:"nickName"` // nickName
	Status   int         `orm:"status"           json:"status"`   // 1:enable 2:disable
	CreateAt *gtime.Time `orm:"create_at"        json:"createAt"` //
	UpdateAt *gtime.Time `orm:"update_at"        json:"updateAt"` //
	DeleteAt *gtime.Time `orm:"delete_at"        json:"deleteAt"` //
}
