// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// AppRole is the golang structure for table app_role.
type AppRole struct {
	Id        int    `orm:"id,primary" json:"id"`        //
	RoleName  string `orm:"role_name"  json:"roleName"`  //
	RoleValue string `orm:"role_value" json:"roleValue"` //
}
