// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// AppUserRole is the golang structure for table app_user_role.
type AppUserRole struct {
	Id     int `orm:"id,primary" json:"id"`     //
	UserId int `orm:"user_id"    json:"userId"` //
	RoleId int `orm:"role_id"    json:"roleId"` //
}
