// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gf-Vben/app/service/internal/dao/internal"
)

// internalPermissionDao is internal type for wrapping internal DAO implements.
type internalPermissionDao = *internal.PermissionDao

// permissionDao is the data access object for table permission.
// You can define custom methods on it to extend its functionality as you wish.
type permissionDao struct {
	internalPermissionDao
}

var (
	// Permission is globally public accessible object for table permission operations.
	Permission = permissionDao{
		internal.NewPermissionDao(),
	}
)

// Fill with you ideas below.
