// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// CasbinRule is the golang structure for table casbin_rule.
type CasbinRule struct {
	Ptype string `json:"ptype" ` //
	V0    string `json:"v0"    ` //
	V1    string `json:"v1"    ` //
	V2    string `json:"v2"    ` //
	V3    string `json:"v3"    ` //
	V4    string `json:"v4"    ` //
	V5    string `json:"v5"    ` //
}
