// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Permission is the golang structure for table permission.
type Permission struct {
	Id       int64       `json:"id"       ` //
	Parent   int64       `json:"parent"   ` //
	Name     string      `json:"name"     ` //
	Desc     string      `json:"desc"     ` //
	CreateAt *gtime.Time `json:"createAt" ` //
	UpdateAt *gtime.Time `json:"updateAt" ` //
	DeleteAt *gtime.Time `json:"deleteAt" ` //
	Tag      string      `json:"tag"      ` //
}
