// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Role is the golang structure for table role.
type Role struct {
	Id         int64       `json:"id"         ` //
	Name       string      `json:"name"       ` //
	CreateAt   *gtime.Time `json:"createAt"   ` //
	UpdateAt   *gtime.Time `json:"updateAt"   ` //
	DeleteAt   *gtime.Time `json:"deleteAt"   ` //
	Value      string      `json:"value"      ` //
	Desc       string      `json:"desc"       ` //
	Permission int         `json:"permission" ` //
}
