// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       int64       `json:"id"       ` //
	Username string      `json:"username" ` //
	Password string      `json:"password" ` //
	Status   int         `json:"status"   ` //
	CreateAt *gtime.Time `json:"createAt" ` //
	UpdateAt *gtime.Time `json:"updateAt" ` //
	DeleteAt *gtime.Time `json:"deleteAt" ` //
}
