// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"Gf-Vben/app/dao/internal"
)

// appUserRoleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type appUserRoleDao struct {
	internal.AppUserRoleDao
}

var (
	// AppUserRole is globally public accessible object for table app_user_role operations.
	AppUserRole = appUserRoleDao{
		internal.AppUserRole,
	}
)

// Fill with you ideas below.
