// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"Gf-Vben/app/dao/internal"
)

// appRoleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type appRoleDao struct {
	internal.AppRoleDao
}

var (
	// AppRole is globally public accessible object for table app_role operations.
	AppRole = appRoleDao{
		internal.AppRole,
	}
)

// Fill with you ideas below.
