// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gf-Vben/internal/dao/internal"
)

// internalRouterDao is internal type for wrapping internal DAO implements.
type internalRouterDao = *internal.RouterDao

// routerDao is the data access object for table router.
// You can define custom methods on it to extend its functionality as you wish.
type routerDao struct {
	internalRouterDao
}

var (
	// Router is globally public accessible object for table router operations.
	Router = routerDao{
		internal.NewRouterDao(),
	}
)

// Fill with you ideas below.
